#!/bin/sh

swift-init all stop

find /var/log/swift -type f -exec rm -f {} \;

umount /srv/node/sdb1

mkfs.xfs -f -i size=1024 /srv/swift-disk

mount /srv/node/sdb1

chown swift:swift /srv/node/sdb1

rm -f /var/log/debug /var/log/messages /var/log/rsyncd.log /var/log/syslog

service rsyslog restart

service rsync restart

service memcached restart
